spring:
  application:
    name: feipi
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:1207/fipi?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: "021207"
  redis:
    host: 192.168.200.130
    port: 6379
    password: 021207...
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
  mvc:
    hiddenmethod:
      filter:
        enabled: true
feipi:
  path: D:\code\javacode\feipi\src\main\resources\backend\images\dish_picture\
#  resources:
#    static-locations:
#      - classpath:/backend/
#      - classpath:/front/